apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: typercloud-prod

resources:
  - ../../base

patches:
  - path: patch-replicas.yaml

images:
  - name: typercloud/backend
    newName: ghcr.io/mwatroba9092/TyperCloud/backend
    newTag: prod
  - name: typercloud/frontend
    newName: ghcr.io/mwatroba9092/TyperCloud/frontend
    newTag: prod
  - name: typercloud/worker
    newName: ghcr.io/mwatroba9092/TyperCloud/worker
    newTag: prod
