apiVersion: v1
kind: ConfigMap
metadata:
  name: typercloud-config
  labels:
    app.kubernetes.io/part-of: typercloud
data:
  REDIS_URL: "redis://redis:6379/0"
  REDIS_CHANNEL: "match_finished"
  OIDC_ISSUER: "http://auth.typercloud.local"
  OIDC_JWKS_URL: "http://zitadel:8080/oauth/v2/keys"
  OIDC_USERINFO_URL: "http://zitadel:8080/oidc/v1/userinfo"
  OIDC_AUDIENCE: "375085643967037445"
  OIDC_ROLES_CLAIM: "urn:zitadel:iam:org:project:roles"
  API_URL: "http://backend:8000"
  OIDC_CLIENT_ID: "375085643967037445"
  OIDC_INTERNAL_URL: "http://zitadel:8080"
  OIDC_REDIRECT_URI: "http://app.typercloud.local/"
  OIDC_POST_LOGOUT_REDIRECT_URI: "http://app.typercloud.local/"
  OIDC_SCOPE: "openid profile email urn:zitadel:iam:org:project:roles"
