apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: typercloud

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.example.yaml
  - postgres-statefulset.yaml
  - auth-statefulset.yaml
  - redis-deployment.yaml
  - backend-deployment.yaml
  - backend-pdb.yaml
  - frontend-deployment.yaml
  - worker-deployment.yaml
  - ingress.yaml
  - networking/networkpolicy.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: typercloud
    includeSelectors: false
