apiVersion: v1
kind: Secret
metadata:
  name: typercloud-secret
  labels:
    app.kubernetes.io/part-of: typercloud
type: Opaque
data:
  POSTGRES_USER: dHlwZXI=
  POSTGRES_PASSWORD: dHlwZXJwYXNz
  POSTGRES_DB: dHlwZXI=
  DATABASE_URL: cG9zdGdyZXNxbCtwc3ljb3BnMjovL3R5cGVyOnR5cGVycGFzc0Bwb3N0Z3Jlczo1NDMyL3R5cGVy
  ZITADEL_DB_NAME: eml0YWRlbA==
  ZITADEL_MASTERKEY: TWFzdGVya2V5TmVlZHNUb0hhdmUzMkNoYXJhY3RlciE=
