# PRZYKLADOWY Secret z wartosciami DEMO (base64). Pozwala od razu uruchomic
# stack na potrzeby zajec. PRZED realnym deployem PODMIEN wszystkie hasla!
# Kodowanie base64 != szyfrowanie. Dekodowanie kontrolne: echo "<val>" | base64 -d
#
# Plik jest zaciagany przez kustomization.yaml jako 'typercloud-secret'.
apiVersion: v1
kind: Secret
metadata:
  name: typercloud-secret
  labels:
    app.kubernetes.io/part-of: typercloud
type: Opaque
data:
  # typer
  POSTGRES_USER: dHlwZXI=
  # typerpass
  POSTGRES_PASSWORD: dHlwZXJwYXNz
  # typer
  POSTGRES_DB: dHlwZXI=
  # postgresql+psycopg2://typer:typerpass@postgres:5432/typer
  DATABASE_URL: cG9zdGdyZXNxbCtwc3ljb3BnMjovL3R5cGVyOnR5cGVycGFzc0Bwb3N0Z3Jlczo1NDMyL3R5cGVy
  # zitadel  (nazwa osobnej bazy dla serwera autoryzacji)
  ZITADEL_DB_NAME: eml0YWRlbA==
  # MasterkeyNeedsToHave32Character!  (dokladnie 32 znaki - wymog Zitadel)
  ZITADEL_MASTERKEY: TWFzdGVya2V5TmVlZHNUb0hhdmUzMkNoYXJhY3RlciE=
