apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: typercloud-dev

resources:
  - ../../base

patches:
  - path: patch-replicas.yaml

images:
  - name: typercloud/backend
    newName: ghcr.io/mwatroba9092/typercloud/backend
    newTag: dev
  - name: typercloud/frontend
    newName: ghcr.io/mwatroba9092/typercloud/frontend
    newTag: dev
  - name: typercloud/worker
    newName: ghcr.io/mwatroba9092/typercloud/worker
    newTag: dev
